// src/utils/seedData.js - Demo data for Takwine platform

export const SEED_USERS = [
    {
        id: 'user_1',
        name: 'Yasmine Bencherif',
        email: 'yasmine@takwine.dz',
        password: 'password123', // In real app, this would be hashed
        filiere: 'Informatique',
        annee: '3ème année',
        bio: 'Passionnée par l\'IA et le développement web. Je partage mes ressources et j\'aime collaborer sur des défis.',
        avatar: null,
        avatarColor: '#6366f1',
        points: 1250,
        badges: ['🏆 Top Contributeur', '⚡ Challenge Master', '📚 Ressource Star'],
        postsCount: 12,
        challengesWon: 5,
        joinedAt: '2024-09-15T08:00:00Z',
    },
    {
        id: 'user_2',
        name: 'Karim Ouali',
        email: 'karim@takwine.dz',
        password: 'password123',
        filiere: 'Mathématiques',
        annee: '2ème année',
        bio: 'Matheux dans l\'âme, j\'adore vulgariser les concepts complexes.',
        avatar: null,
        avatarColor: '#f59e0b',
        points: 980,
        badges: ['🎯 Problème Solver', '📐 Math Wizard'],
        postsCount: 8,
        challengesWon: 3,
        joinedAt: '2024-09-20T10:00:00Z',
    },
    {
        id: 'user_3',
        name: 'Lina Hamidi',
        email: 'lina@takwine.dz',
        password: 'password123',
        filiere: 'Physique',
        annee: '1ère année',
        bio: 'Curieuse de tout, j\'explore le monde de la physique quantique.',
        avatar: null,
        avatarColor: '#10b981',
        points: 540,
        badges: ['🌟 Rising Star'],
        postsCount: 4,
        challengesWon: 1,
        joinedAt: '2024-10-05T09:00:00Z',
    },
];

const now = new Date();
const hoursAgo = (h) => new Date(now - h * 3600000).toISOString();

export const SEED_POSTS = [
    {
        id: 'post_1',
        authorId: 'user_1',
        type: 'resource',
        subject: 'Informatique',
        filiere: 'Informatique',
        title: 'Guide complet : Algorithmes de tri en Python',
        content: 'Voici un guide que j\'ai préparé sur les différents algorithmes de tri : Bubble Sort, Quick Sort, Merge Sort... avec complexités temporelles et exemples pratiques en Python. 🐍\n\nLes algorithmes de tri sont fondamentaux en informatique. Maîtriser leurs complexités vous donnera un avantage énorme en entretien et en concours.',
        imageUrl: null,
        link: 'https://docs.python.org/fr/3/howto/sorting.html',
        likes: 42,
        likedBy: ['user_2', 'user_3'],
        commentsCount: 7,
        createdAt: hoursAgo(2),
        rsvpBy: [],
        rsvpCount: 0,
    },
    {
        id: 'post_2',
        authorId: 'user_2',
        type: 'challenge',
        subject: 'Mathématiques',
        filiere: 'Mathématiques',
        title: '🏆 Défi : Intégrales triples — Qui relève le défi ?',
        content: 'Défi du jour ! 📐\n\nCalculez l\'intégrale triple suivante :\n∭_V (x² + y² + z²) dV\n\noù V est la boule de rayon 2 centrée à l\'origine.\n\nPostez votre solution complète en commentaire avec la méthode utilisée. Votes pour la meilleure solution ! Les 3 meilleures gagnent des points. 🎯',
        imageUrl: null,
        link: null,
        likes: 28,
        likedBy: ['user_1'],
        commentsCount: 12,
        deadline: new Date(now.getTime() + 48 * 3600000).toISOString(),
        createdAt: hoursAgo(5),
        rsvpBy: [],
        rsvpCount: 0,
    },
    {
        id: 'post_3',
        authorId: 'user_3',
        type: 'event',
        subject: 'Physique',
        filiere: 'Physique',
        title: '🔴 LIVE — Introduction à la mécanique quantique',
        content: 'Je vous invite à une mini-session live sur les bases de la mécanique quantique !\n\n📅 Date: Vendredi 7 Mars 2026\n⏰ Heure: 18h00 (Heure d\'Alger)\n🔗 Lien: Google Meet\n\nNous aborderons : Dualité onde-corpuscule, Principe d\'incertitude de Heisenberg, Équation de Schrödinger.\n\nTous niveaux bienvenus ! 🌌',
        imageUrl: null,
        videoLink: 'https://meet.google.com/abc-defg-hij',
        eventDate: '2026-03-07T18:00:00Z',
        likes: 65,
        likedBy: ['user_1', 'user_2'],
        commentsCount: 18,
        rsvpBy: ['user_1', 'user_2'],
        rsvpCount: 23,
        createdAt: hoursAgo(8),
    },
    {
        id: 'post_4',
        authorId: 'user_1',
        type: 'resource',
        subject: 'Informatique',
        filiere: 'Informatique',
        title: 'Résumé complet des Design Patterns (GoF)',
        content: 'Après des semaines de travail, voici mon résumé des 23 patterns GoF avec des exemples en Python et Java. Idéal pour réviser avant les exams ou préparer un entretien tech ! 💻\n\nPatterns couverts :\n• Création : Singleton, Factory, Abstract Factory, Builder, Prototype\n• Structure : Adapter, Bridge, Composite, Decorator, Facade, Flyweight, Proxy\n• Comportement : Chain of Responsibility, Command, Iterator, Observer, Strategy...',
        imageUrl: null,
        link: null,
        likes: 89,
        likedBy: ['user_2', 'user_3'],
        commentsCount: 15,
        createdAt: hoursAgo(24),
        rsvpBy: [],
        rsvpCount: 0,
    },
    {
        id: 'post_5',
        authorId: 'user_2',
        type: 'challenge',
        subject: 'Mathématiques',
        filiere: 'Tous',
        title: '🎯 Mini-Défi Logique : La suite mystérieuse',
        content: 'Trouvez le terme général de cette suite :\n\n1, 1, 2, 3, 5, 8, 13, 21, 34, ...\n\nBonus : Démontrez la formule de Binet permettant de calculer directement le n-ème terme ! 🌀\n\nProuvez aussi la convergence du rapport an+1/an quand n → ∞. Bonne chance ! 🍀',
        imageUrl: null,
        link: null,
        likes: 34,
        likedBy: ['user_1', 'user_3'],
        commentsCount: 9,
        deadline: new Date(now.getTime() + 24 * 3600000).toISOString(),
        createdAt: hoursAgo(36),
        rsvpBy: [],
        rsvpCount: 0,
    },
    {
        id: 'post_6',
        authorId: 'user_3',
        type: 'event',
        subject: 'Physique',
        filiere: 'Physique',
        title: '📡 Atelier Electronique — Construire un oscillateur RC',
        content: 'Atelier pratique en présentiel !\n📍 Lieu: Labo de Physique, Bâtiment C\n📅 Date: Samedi 8 Mars 2026\n⏰ Heure: 14h00\n\nNous allons construire un oscillateur RC simple et analyser les signaux à l\'oscilloscope. Matériel fourni. Places limitées à 20 participants !',
        imageUrl: null,
        videoLink: null,
        eventDate: '2026-03-08T14:00:00Z',
        likes: 21,
        likedBy: ['user_1'],
        commentsCount: 5,
        rsvpBy: ['user_1'],
        rsvpCount: 12,
        createdAt: hoursAgo(48),
    },
];

export const SEED_COMMENTS = [
    // Post 1 comments
    { id: 'c1', postId: 'post_1', parentId: null, authorId: 'user_2', content: 'Excellente ressource ! J\'ai fait un résumé similaire mais tu as ajouté les cas d\'utilisation concrèts que je n\'avais pas. Merci !', likes: 5, likedBy: ['user_1'], createdAt: hoursAgo(1.5) },
    { id: 'c2', postId: 'post_1', parentId: null, authorId: 'user_3', content: 'C\'est exactement ce dont j\'avais besoin pour les révisions. Le QuickSort m\'a toujours posé des problèmes avec les cas de pivot mal choisi.', likes: 3, likedBy: [], createdAt: hoursAgo(1) },
    { id: 'c3', postId: 'post_1', parentId: 'c2', authorId: 'user_1', content: 'Pour le pivot justement, la technique du "médiane des trois" est souvent utilisée en pratique pour éviter le pire cas O(n²) !', likes: 2, likedBy: ['user_2'], createdAt: hoursAgo(0.8) },

    // Post 2 comments
    { id: 'c4', postId: 'post_2', parentId: null, authorId: 'user_1', content: '∭_V (x²+y²+z²)dV = 4π/5 · r⁵ = 4π/5 · 32 = 128π/5\n\nJ\'ai utilisé les coordonnées sphériques avec r ∈ [0,2], θ ∈ [0,π], φ ∈ [0,2π]. Le jacobien en sphérique donne r²sin(θ).', likes: 12, likedBy: ['user_2', 'user_3'], createdAt: hoursAgo(4) },
    { id: 'c5', postId: 'post_2', parentId: 'c4', authorId: 'user_2', content: '✅ Correct ! Belle maîtrise des coordonnées sphériques. +30 points pour Yasmine !', likes: 4, likedBy: ['user_1'], createdAt: hoursAgo(3.5) },

    // Post 3 comments
    { id: 'c6', postId: 'post_3', parentId: null, authorId: 'user_1', content: 'Je participe ! La mécanique quantique m\'a toujours intrigué. Hâte de voir le chat de Schrödinger expliqué clairement 😄', likes: 8, likedBy: ['user_2'], createdAt: hoursAgo(7) },
    { id: 'c7', postId: 'post_3', parentId: null, authorId: 'user_2', content: 'Très bonne initiative Lina ! Est-ce qu\'on peut poser des questions en direct ?', likes: 3, likedBy: [], createdAt: hoursAgo(6) },
    { id: 'c8', postId: 'post_3', parentId: 'c7', authorId: 'user_3', content: 'Bien sûr ! Il y aura une session Q&A de 20min à la fin. 🎤', likes: 2, likedBy: ['user_2'], createdAt: hoursAgo(5.5) },
];
